{{- if not .Values.backend.slack.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "darts-league.backendSlackSecretName" . }}
  labels:
    {{- include "darts-league.backendLabels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_BOT_TOKEN: {{ .Values.backend.slack.botToken | quote }}
{{- end }}
