apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "darts-league.backendName" . }}
  labels:
    {{- include "darts-league.backendLabels" . | nindent 4 }}
data:
  HTTP_ADDRESS: {{ .Values.backend.env.httpAddress | quote }}
  INSTANCE_NAME: {{ .Values.backend.env.instanceName | quote }}
  PUBLIC_BASE_URL: {{ .Values.backend.env.publicBaseUrl | default "" | quote }}
  APP_TIMEZONE: {{ .Values.backend.env.appTimezone | quote }}
  SLACK_PUBLIC_CHANNEL_ID: {{ .Values.backend.env.slackPublicChannelId | quote }}
  SLACK_ADMIN_CHANNEL_ID: {{ .Values.backend.env.slackAdminChannelId | quote }}
  AWS_REGION: {{ .Values.backend.env.awsRegion | default "" | quote }}
  SQS_POLL_INTERVAL: {{ .Values.backend.env.sqsPollInterval | default "15m" | quote }}
  {{- if .Values.backend.env.sqsQueueUrl }}
  SQS_QUEUE_URL: {{ .Values.backend.env.sqsQueueUrl | quote }}
  {{- end }}
  {{- if .Values.backend.env.appNow }}
  APP_NOW: {{ .Values.backend.env.appNow | quote }}
  {{- end }}
