ALTER TABLE seasons ADD COLUMN IF NOT EXISTS game_variant TEXT NOT NULL DEFAULT '501';
ALTER TABLE seasons ADD COLUMN IF NOT EXISTS legs_to_win INTEGER NOT NULL DEFAULT 3;
ALTER TABLE seasons ADD COLUMN IF NOT EXISTS games_per_week INTEGER NOT NULL DEFAULT 1;
