version = 0.1

[default.deploy.parameters]
stack_name = "cardiffDarts"
resolve_s3 = true
s3_prefix = "cardiffDarts"
region = "eu-west-1"
profile = "darts"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AllowedOrigin=\"https://play.autodarts.com\""
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
